name: 🤖 Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - langs/**

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Restore node modules
        uses: masteos/always-upload-cache@v3.0.1
        with:
          path: node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

      - name: Install node modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn install

      - name: Generate lib
        run: yarn sync
  
      - name: Commit changes
        uses: EndBug/add-and-commit@v8
        with:
          message: "feat: update lib"
          default_author: github_actions

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v2.7.0
        with:
          semantic_version: 17
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
